### ISSUE TITLE
Unable to open/create new temporary directory.

### ISSUE THREAD

**Issue by PaulSchulz** [clojurewerkz/envision#3]
Greetings,
I am using Ubuntu 16.10, which for some reason has the temporary directory set to '/tmp'
The directory that envision tries to create is something like: /tmpenvision-1488714813581-2793081121

I am unsure of how 'FileUtils getTempDirectoryPath' gets the temporary directory.

Setting environment variables TMP, TEMP, TMPDIR does not make any difference. I would like to be able run the clojure code from my emacs/cider environment.

Paul

**Comment by michaelklishin** [comment]
The JVM has its own property for setting a temporary directory. `/tmpenvision-1488714813581-2793081121` seems to have a missing separator, is this what you are hinting at?

**Comment by PaulSchulz** [comment]
Yes, thanks.. I put a separator in my fork, and the directory is now created.. but I don't think it is being populated properly as I'm getting the following errors in the python webserver.

127.0.0.1 - - [05/Mar/2017 23:21:15] "GET /assets/cljs/goog/base.js HTTP/1.1" 200 -
127.0.0.1 - - [05/Mar/2017 23:21:15] code 404, message File not found
127.0.0.1 - - [05/Mar/2017 23:21:15] "GET /assets/cljs/main.js HTTP/1.1" 404 -
127.0.0.1 - - [05/Mar/2017 23:21:16] code 404, message File not found
127.0.0.1 - - [05/Mar/2017 23:21:16] "GET /assets/cljs/goog/deps.js HTTP/1.1" 404 -
127.0.0.1 - - [05/Mar/2017 23:21:16] code 404, message File not found
127.0.0.1 - - [05/Mar/2017 23:21:16] "GET /assets/cljs/main.js HTTP/1.1" 404 -

**Comment by PaulSchulz** [comment]
(I manually copied goog/base.js from another project, otherwise it was missing as well.)

**Comment by michaelklishin** [comment]
@PaulSchulz mind submitting a PR with your change?

**Comment by PaulSchulz** [comment]
Done
