### ISSUE TITLE
Get error with lein when setting dependency in project.clj (Expect TLS)

### ISSUE THREAD

**Issue by PaulSchulz** [clojurewerkz/envision#5]
With a freshly created project via 'lein new app ps-clj-testing', I get the following error when I add the dependency to project.clj file
>>>>>
(defproject ps-clj-testing "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.8.0"]
                 [clojurewerkz/envision "0.1.0-SNAPSHOT"]  ]
  :main ^:skip-aot ps-clj-testing.core
  :target-path "target/%s"
  :profiles {:uberjar {:aot :all}})
>>>>>>

$ lein repl
Tried to use insecure HTTP repository without TLS.
This is almost certainly a mistake; however in rare cases where it's
intentional please see `lein help faq` for details.

Removing/commenting out the dependancy allow me to get ot the repl prompt.
$lein repl
nREPL server started on port 38599 on host 127.0.0.1 - nrepl://127.0.0.1:38599
REPL-y 0.3.7, nREPL 0.2.12
Clojure 1.8.0
OpenJDK 64-Bit Server VM 1.8.0_151-8u151-b12-0ubuntu0.17.10.2-b12
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

$ lein version
Leiningen 2.8.1 on Java 1.8.0_151 OpenJDK 64-Bit Server VM

Leiningen FAQ indicated that it may be due to a dependancy not using a HTTPS URL.
https://github.com/technomancy/leiningen/blob/master/doc/FAQ.md (Search for 'insecure HTTP')

**Comment by michaelklishin** [comment]
My only guess is that it's due to the fact that Envision used HTTP for external repo URLs. That's corrected in master, feel free to compile from source, install a snapshot into your local repo and compare.
